insert into items (id, track, sort_order, title, description, metadata) values
('se-plan-w1-1','plan',1,'Architecture patterns, C4, DDD basics','Draw C4 diagrams for the ERP; write ADR-001.','{"week":1,"month":1,"hours":22,"kind":"focus"}'::jsonb),
('se-plan-w1-2','plan',2,'Read A Philosophy of Software Design (Ousterhout)',NULL,'{"week":1,"month":1,"hours":22,"kind":"reading"}'::jsonb),
('se-plan-w1-3','plan',3,'C4 model docs (reading)',NULL,'{"week":1,"month":1,"hours":22,"kind":"reading"}'::jsonb),
('se-plan-w1-4','plan',4,'Draw C4 diagrams + write ADR-001',NULL,'{"week":1,"month":1,"hours":22,"kind":"hands_on"}'::jsonb),
('se-plan-w2-1','plan',5,'Clean Architecture, VSA, modular monolith','Refactor one ERP module into clean layers.','{"week":2,"month":1,"hours":22,"kind":"focus"}'::jsonb),
('se-plan-w2-2','plan',6,'Read Clean Architecture (Martin) ch1-10; VickyBytes architecture roadmap',NULL,'{"week":2,"month":1,"hours":22,"kind":"reading"}'::jsonb),
('se-plan-w2-3','plan',7,'Refactor one ERP module into clean layers',NULL,'{"week":2,"month":1,"hours":22,"kind":"hands_on"}'::jsonb),
('se-plan-w3-1','plan',8,'SRS/BRD/ADR writing; API documentation','Write SRS for next module; publish OpenAPI spec.','{"week":3,"month":1,"hours":22,"kind":"focus"}'::jsonb),
('se-plan-w3-2','plan',9,'Read Asana SRS guide; OpenAPI docs',NULL,'{"week":3,"month":1,"hours":22,"kind":"reading"}'::jsonb),
('se-plan-w3-3','plan',10,'Write SRS for next module + publish OpenAPI spec',NULL,'{"week":3,"month":1,"hours":22,"kind":"hands_on"}'::jsonb),
('se-plan-w4-1','plan',11,'Database design, indexing, schema evolution','Audit slow queries; add 3 indexes; document strategy.','{"week":4,"month":1,"hours":22,"kind":"focus"}'::jsonb),
('se-plan-w4-2','plan',12,'Read Designing Data-Intensive Applications (Kleppmann) ch2-3; Postgres indexing guides',NULL,'{"week":4,"month":1,"hours":22,"kind":"reading"}'::jsonb),
('se-plan-w4-3','plan',13,'Audit slow queries + add 3 indexes + document strategy',NULL,'{"week":4,"month":1,"hours":22,"kind":"hands_on"}'::jsonb),
('se-plan-w5-1','plan',14,'Testing pyramid; unit and integration tests','Add Jest unit tests + Supertest integration tests.','{"week":5,"month":2,"hours":22,"kind":"focus"}'::jsonb),
('se-plan-w5-2','plan',15,'Read CircleCI testing pyramid guide; Jest docs',NULL,'{"week":5,"month":2,"hours":22,"kind":"reading"}'::jsonb),
('se-plan-w5-3','plan',16,'Add Jest unit tests + Supertest integration tests',NULL,'{"week":5,"month":2,"hours":22,"kind":"hands_on"}'::jsonb),
('se-plan-w6-1','plan',17,'CI/CD, quality gates, code review','Set up GitHub Actions; create PR template; enforce lint.','{"week":6,"month":2,"hours":22,"kind":"focus"}'::jsonb),
('se-plan-w6-2','plan',18,'Read GitHub Actions docs; PR template guides',NULL,'{"week":6,"month":2,"hours":22,"kind":"reading"}'::jsonb),
('se-plan-w6-3','plan',19,'Set up GitHub Actions + create PR template + enforce lint',NULL,'{"week":6,"month":2,"hours":22,"kind":"hands_on"}'::jsonb),
('se-plan-w7-1','plan',20,'OWASP API Top 10; secure coding','Audit API; add ownership checks + rate limiting.','{"week":7,"month":2,"hours":22,"kind":"focus"}'::jsonb),
('se-plan-w7-2','plan',21,'Read OWASP cheat sheets; Zuplo API security guide',NULL,'{"week":7,"month":2,"hours":22,"kind":"reading"}'::jsonb),
('se-plan-w7-3','plan',22,'Audit API + add ownership checks + rate limiting',NULL,'{"week":7,"month":2,"hours":22,"kind":"hands_on"}'::jsonb),
('se-plan-w8-1','plan',23,'Observability, SRE basics, runbooks','Add structured logging + alerts; write 2 runbooks.','{"week":8,"month":2,"hours":22,"kind":"focus"}'::jsonb),
('se-plan-w8-2','plan',24,'Read Google SRE book intro; Better Stack docs',NULL,'{"week":8,"month":2,"hours":22,"kind":"reading"}'::jsonb),
('se-plan-w8-3','plan',25,'Add structured logging + alerts + write 2 runbooks',NULL,'{"week":8,"month":2,"hours":22,"kind":"hands_on"}'::jsonb),
('se-plan-w9-1','plan',26,'Deployment routes: PaaS, IaaS, containers','Dockerize API; run locally with Docker Compose.','{"week":9,"month":3,"hours":22,"kind":"focus"}'::jsonb),
('se-plan-w9-2','plan',27,'Read Render/Railway/Fly.io docs; Docker Getting Started',NULL,'{"week":9,"month":3,"hours":22,"kind":"reading"}'::jsonb),
('se-plan-w9-3','plan',28,'Dockerize API + run locally with Docker Compose',NULL,'{"week":9,"month":3,"hours":22,"kind":"hands_on"}'::jsonb),
('se-plan-w10-1','plan',29,'Caching, performance, scalability','Add Redis caching for read-heavy ERP endpoint.','{"week":10,"month":3,"hours":22,"kind":"focus"}'::jsonb),
('se-plan-w10-2','plan',30,'Read caching strategy guides; watch System Design Interview videos',NULL,'{"week":10,"month":3,"hours":22,"kind":"video"}'::jsonb),
('se-plan-w10-3','plan',31,'Add Redis caching for a read-heavy endpoint',NULL,'{"week":10,"month":3,"hours":22,"kind":"hands_on"}'::jsonb),
('se-plan-w11-1','plan',32,'Client documentation, SLAs, change control','Write SOW template; define SLA for clients.','{"week":11,"month":3,"hours":22,"kind":"focus"}'::jsonb),
('se-plan-w11-2','plan',33,'Read proposal/SOW templates; support playbook templates',NULL,'{"week":11,"month":3,"hours":22,"kind":"reading"}'::jsonb),
('se-plan-w11-3','plan',34,'Write SOW template + define SLA for clients',NULL,'{"week":11,"month":3,"hours":22,"kind":"hands_on"}'::jsonb),
('se-plan-w12-1','plan',35,'Technical debt, long-term maintenance','Create debt inventory; allocate 20% of next sprint to debt.','{"week":12,"month":3,"hours":22,"kind":"focus"}'::jsonb),
('se-plan-w12-2','plan',36,'Read technical debt OKR playbook',NULL,'{"week":12,"month":3,"hours":22,"kind":"reading"}'::jsonb),
('se-plan-w12-3','plan',37,'Create debt inventory + allocate 20% of next sprint to debt',NULL,'{"week":12,"month":3,"hours":22,"kind":"hands_on"}'::jsonb),
('se-proj-1','project',1,'Draw Your Architecture','Create C4 Context + Container diagrams; identify bounded contexts; write ADR-001 on the modular monolith.','{}'::jsonb),
('se-proj-2','project',2,'Documentation Sprint','Write an SRS for the next ERP module; a BRD for one client engagement; an OpenAPI spec; publish with Swagger UI or Scalar.','{}'::jsonb),
('se-proj-3','project',3,'Add Observability','Structured logging; connect to Better Stack/Logtail free tier; alerts for 5xx + high latency; two runbooks.','{}'::jsonb),
('se-proj-4','project',4,'Testing Ramp-Up','Jest unit tests for one core module; Supertest integration for auth + one business API; one Playwright E2E for login→dashboard; GitHub Actions on every PR.','{}'::jsonb),
('se-proj-5','project',5,'Security Hardening','Audit API against OWASP API Top 10; per-resource ownership checks; rate limiting; run npm audit and triage.','{}'::jsonb),
('se-proj-6','project',6,'Database Optimization','Find the 5 slowest queries via Supabase logs/pg_stat_statements; add indexes and measure; document the strategy.','{}'::jsonb),
('se-proj-7','project',7,'Deployment Portability','Dockerize the Node.js API; run locally with Docker Compose including Postgres; document one-command full-stack local run.','{}'::jsonb),
('se-proj-8','project',8,'Evaluate New Hosting','Deploy a staging copy to Railway or Fly.io; compare cost, cold-start, deploy experience vs Render; write an ADR.','{}'::jsonb),
('se-topic-1','topic',1,'System Architecture & Design Patterns',NULL,'{"section":1,"subsections":5}'::jsonb),
('se-topic-2','topic',2,'Development (Technical) Documentation',NULL,'{"section":2,"subsections":5}'::jsonb),
('se-topic-3','topic',3,'Business & Client Documentation',NULL,'{"section":3,"subsections":4}'::jsonb),
('se-topic-4','topic',4,'Tech Stack & Deployment Decision Framework',NULL,'{"section":4,"subsections":6}'::jsonb),
('se-topic-5','topic',5,'Post-Deployment Support & SRE',NULL,'{"section":5,"subsections":6}'::jsonb),
('se-topic-6','topic',6,'Engineering Discipline: Quality, Security, Maintainability',NULL,'{"section":6,"subsections":8}'::jsonb),
('se-topic-7','topic',7,'Hands-On Projects Applied to Your ERP',NULL,'{"section":7,"subsections":8}'::jsonb),
('se-topic-8','topic',8,'Weekly Study Plan',NULL,'{"section":8,"subsections":4}'::jsonb),
('se-topic-9','topic',9,'Recommended Resources',NULL,'{"section":9,"subsections":4}'::jsonb),
('se-topic-10','topic',10,'Quick Reference: Decisions You Will Face Soon',NULL,'{"section":10,"subsections":6}'::jsonb),
('se-topic-11','topic',11,'Conclusion: Your Path Forward',NULL,'{"section":11,"subsections":0}'::jsonb),
('se-topic-12','topic',12,'Deep Dive: Software Design Patterns',NULL,'{"section":12,"subsections":7}'::jsonb),
('se-topic-13','topic',13,'Deep Dive: Types of Software Testing',NULL,'{"section":13,"subsections":10}'::jsonb),
('se-topic-14','topic',14,'Deep Dive: Core Production Concepts',NULL,'{"section":14,"subsections":7}'::jsonb),
('se-topic-15','topic',15,'Sources and References',NULL,'{"section":15,"subsections":7}'::jsonb),
('se-res-1','resource',1,'A Philosophy of Software Design — Ousterhout',NULL,'{"type":"book","author":"John Ousterhout","url":"https://www.amazon.com/Philosophy-Software-Design-John-Ousterhout/dp/1732902209"}'::jsonb),
('se-res-2','resource',2,'Clean Architecture — Robert C. Martin',NULL,'{"type":"book","author":"Robert C. Martin","url":"https://www.amazon.com/Clean-Architecture-Craftsmans-Software-Structure/dp/0134494164"}'::jsonb),
('se-res-3','resource',3,'Designing Data-Intensive Applications — Kleppmann',NULL,'{"type":"book","author":"Martin Kleppmann","url":"https://www.amazon.com/Designing-Data-Intensive-Applications-Reliable-Maintainable/dp/1449373321"}'::jsonb),
('se-res-4','resource',4,'Domain-Driven Design — Eric Evans',NULL,'{"type":"book","author":"Eric Evans","url":"https://www.amazon.com/Domain-Driven-Design-Tackling-Complexity-Software/dp/0321125215"}'::jsonb),
('se-res-5','resource',5,'Release It! — Michael Nygard',NULL,'{"type":"book","author":"Michael Nygard","url":"https://www.oreilly.com/library/view/release-it-2nd/9781680505264/"}'::jsonb),
('se-res-6','resource',6,'The Phoenix Project / The Unicorn Project — Gene Kim',NULL,'{"type":"book","author":"Gene Kim","url":"https://www.amazon.com/Phoenix-Project-DevOps-Helping-Business/dp/1942788290"}'::jsonb),
('se-res-7','resource',7,'Building Microservices — Sam Newman',NULL,'{"type":"book","author":"Sam Newman","url":"https://www.oreilly.com/library/view/building-microservices-2nd/9781492034025/"}'::jsonb),
('se-res-8','resource',8,'Software Architecture: The Hard Parts — Neal Ford et al.',NULL,'{"type":"book","author":"Neal Ford","url":"https://www.oreilly.com/library/view/software-architecture/9781492085296/"}'::jsonb),
('se-res-9','resource',9,'Fundamentals of Software Architecture, 2nd Ed. — Richards & Ford',NULL,'{"type":"book","author":"Mark Richards & Neal Ford","url":"https://www.oreilly.com/library/view/fundamentals-of-software/9781098114721/"}'::jsonb),
('se-res-10','resource',10,'Head First Design Patterns, 2nd Ed.',NULL,'{"type":"book","url":"https://www.amazon.com/Head-First-Design-Patterns-Brain-Friendly/dp/149207800X"}'::jsonb),
('se-res-11','resource',11,'ByteByteGo (system design)',NULL,'{"type":"video","url":"https://www.youtube.com/@ByteByteGo"}'::jsonb),
('se-res-12','resource',12,'ArjanCodes',NULL,'{"type":"video","url":"https://www.youtube.com/@ArjanCodes"}'::jsonb),
('se-res-13','resource',13,'Fireship',NULL,'{"type":"video","url":"https://www.youtube.com/@Fireship"}'::jsonb),
('se-res-14','resource',14,'Traversy Media',NULL,'{"type":"video","url":"https://www.youtube.com/@TraversyMedia"}'::jsonb),
('se-res-15','resource',15,'freeCodeCamp',NULL,'{"type":"video","url":"https://www.youtube.com/@freecodecamp"}'::jsonb),
('se-res-16','resource',16,'Design Patterns in Plain English — Mosh Hamedani',NULL,'{"type":"video","url":"https://www.youtube.com/watch?v=NU_1StN5Tkk"}'::jsonb),
('se-res-17','resource',17,'8 Design Patterns EVERY Developer Should Know',NULL,'{"type":"video","url":"https://www.youtube.com/watch?v=tAuRQs_d9F8"}'::jsonb),
('se-res-18','resource',18,'Master Software Architecture (GOTO 2025)',NULL,'{"type":"video","url":"https://www.youtube.com/watch?v=ZCrCqbblXjk"}'::jsonb),
('se-res-19','resource',19,'Udemy: Software Architecture & Design of Modern Large Scale Systems',NULL,'{"type":"video","url":"https://www.udemy.com/course/software-architecture-design-of-modern-large-scale-systems/"}'::jsonb),
('se-res-20','resource',20,'Udemy: Modern Software Architecture - Foundation',NULL,'{"type":"video","url":"https://www.udemy.com/course/modern-software-architecture-foundation/"}'::jsonb),
('se-res-21','resource',21,'C4 Model',NULL,'{"type":"doc","url":"https://c4model.com/"}'::jsonb),
('se-res-22','resource',22,'OpenAPI Specification',NULL,'{"type":"doc","url":"https://swagger.io/specification/"}'::jsonb),
('se-res-23','resource',23,'OWASP API Security Top 10',NULL,'{"type":"doc","url":"https://owasp.org/www-project-api-security/"}'::jsonb),
('se-res-24','resource',24,'Google SRE Book',NULL,'{"type":"doc","url":"https://sre.google/sre-book/table-of-contents/"}'::jsonb),
('se-res-25','resource',25,'Docker Getting Started',NULL,'{"type":"doc","url":"https://docs.docker.com/get-started/"}'::jsonb),
('se-res-26','resource',26,'GitHub Actions Documentation',NULL,'{"type":"doc","url":"https://docs.github.com/en/actions"}'::jsonb),
('se-res-27','resource',27,'Jest Documentation',NULL,'{"type":"doc","url":"https://jestjs.io/docs/getting-started"}'::jsonb),
('se-res-28','resource',28,'Playwright Documentation',NULL,'{"type":"doc","url":"https://playwright.dev/docs/intro"}'::jsonb),
('se-res-29','resource',29,'Supabase Documentation',NULL,'{"type":"doc","url":"https://supabase.com/docs"}'::jsonb),
('se-res-30','resource',30,'Render Documentation',NULL,'{"type":"doc","url":"https://docs.render.com/"}'::jsonb),
('se-res-31','resource',31,'Railway Documentation',NULL,'{"type":"doc","url":"https://docs.railway.app/"}'::jsonb),
('se-res-32','resource',32,'Fly.io Documentation',NULL,'{"type":"doc","url":"https://fly.io/docs/"}'::jsonb),
('se-res-33','resource',33,'Designing a Rate Limiter: 4 Algorithms, Real Trade-Offs',NULL,'{"type":"article","url":"https://dev.to/gabrielanhaia/designing-a-rate-limiter-4-algorithms-real-trade-offs-3h5"}'::jsonb),
('se-res-34','resource',34,'How API Rate Limiting Works',NULL,'{"type":"article","url":"https://mohamed-hendawy.medium.com/how-api-rate-limiting-works-fixed-window-token-bucket-sliding-window-explained-c16521f3e0e6"}'::jsonb),
('se-res-35','resource',35,'The different types of testing in software (Atlassian)',NULL,'{"type":"article","url":"https://www.atlassian.com/continuous-delivery/software-testing/types-of-software-testing"}'::jsonb),
('se-res-36','resource',36,'Types of software testing (Tricentis)',NULL,'{"type":"article","url":"https://www.tricentis.com/learn/software-testing-types"}'::jsonb),
('se-res-37','resource',37,'Unit vs Integration vs System vs E2E Testing (Microsoft)',NULL,'{"type":"article","url":"https://microsoft.github.io/code-with-engineering-playbook/automated-testing/e2e-testing/testing-comparison/"}'::jsonb),
('se-res-38','resource',38,'Software requirement document template (Asana)',NULL,'{"type":"article","url":"https://asana.com/resources/software-requirement-document-template"}'::jsonb),
('se-res-39','resource',39,'Trunk-Based Development vs. Gitflow (Flagsmith)',NULL,'{"type":"article","url":"https://www.flagsmith.com/blog/trunk-based-development-vs-gitflow"}'::jsonb),
('se-res-40','resource',40,'Refactoring Guru — Design Patterns',NULL,'{"type":"doc","url":"https://refactoring.guru/design-patterns"}'::jsonb)
on conflict (id) do nothing;
