import type { Item } from './types';

export const SEED_ITEMS: Item[] = [
  // ---- PLAN: 12 weeks (guide §8) ----
  // Month 1: Architecture, Documentation, and Database
  { id: 'se-plan-w1-1', course_id: 'se-realworld', track: 'plan', sort_order: 1, title: 'Architecture patterns, C4, DDD basics',
    description: 'Draw C4 diagrams for the ERP; write ADR-001.',
    metadata: { week: 1, month: 1, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w1-2', course_id: 'se-realworld', track: 'plan', sort_order: 2, title: 'Read A Philosophy of Software Design (Ousterhout)',
    metadata: { week: 1, month: 1, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w1-3', course_id: 'se-realworld', track: 'plan', sort_order: 3, title: 'C4 model docs (reading)',
    metadata: { week: 1, month: 1, hours: 22, kind: 'reading', url: 'https://c4model.com' } },
  { id: 'se-plan-w1-4', course_id: 'se-realworld', track: 'plan', sort_order: 4, title: 'Draw C4 diagrams + write ADR-001',
    metadata: { week: 1, month: 1, hours: 22, kind: 'hands_on' } },

  { id: 'se-plan-w2-1', course_id: 'se-realworld', track: 'plan', sort_order: 5, title: 'Clean Architecture, VSA, modular monolith',
    description: 'Refactor one ERP module into clean layers.',
    metadata: { week: 2, month: 1, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w2-2', course_id: 'se-realworld', track: 'plan', sort_order: 6, title: 'Read Clean Architecture (Martin) ch1-10; VickyBytes architecture roadmap',
    metadata: { week: 2, month: 1, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w2-3', course_id: 'se-realworld', track: 'plan', sort_order: 7, title: 'Refactor one ERP module into clean layers',
    metadata: { week: 2, month: 1, hours: 22, kind: 'hands_on' } },

  { id: 'se-plan-w3-1', course_id: 'se-realworld', track: 'plan', sort_order: 8, title: 'SRS/BRD/ADR writing; API documentation',
    description: 'Write SRS for next module; publish OpenAPI spec.',
    metadata: { week: 3, month: 1, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w3-2', course_id: 'se-realworld', track: 'plan', sort_order: 9, title: 'Read Asana SRS guide; OpenAPI docs',
    metadata: { week: 3, month: 1, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w3-3', course_id: 'se-realworld', track: 'plan', sort_order: 10, title: 'Write SRS for next module + publish OpenAPI spec',
    metadata: { week: 3, month: 1, hours: 22, kind: 'hands_on' } },

  { id: 'se-plan-w4-1', course_id: 'se-realworld', track: 'plan', sort_order: 11, title: 'Database design, indexing, schema evolution',
    description: 'Audit slow queries; add 3 indexes; document strategy.',
    metadata: { week: 4, month: 1, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w4-2', course_id: 'se-realworld', track: 'plan', sort_order: 12, title: 'Read Designing Data-Intensive Applications (Kleppmann) ch2-3; Postgres indexing guides',
    metadata: { week: 4, month: 1, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w4-3', course_id: 'se-realworld', track: 'plan', sort_order: 13, title: 'Audit slow queries + add 3 indexes + document strategy',
    metadata: { week: 4, month: 1, hours: 22, kind: 'hands_on' } },

  // Month 2: Quality, Security, and Operations
  { id: 'se-plan-w5-1', course_id: 'se-realworld', track: 'plan', sort_order: 14, title: 'Testing pyramid; unit and integration tests',
    description: 'Add Jest unit tests + Supertest integration tests.',
    metadata: { week: 5, month: 2, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w5-2', course_id: 'se-realworld', track: 'plan', sort_order: 15, title: 'Read CircleCI testing pyramid guide; Jest docs',
    metadata: { week: 5, month: 2, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w5-3', course_id: 'se-realworld', track: 'plan', sort_order: 16, title: 'Add Jest unit tests + Supertest integration tests',
    metadata: { week: 5, month: 2, hours: 22, kind: 'hands_on' } },

  { id: 'se-plan-w6-1', course_id: 'se-realworld', track: 'plan', sort_order: 17, title: 'CI/CD, quality gates, code review',
    description: 'Set up GitHub Actions; create PR template; enforce lint.',
    metadata: { week: 6, month: 2, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w6-2', course_id: 'se-realworld', track: 'plan', sort_order: 18, title: 'Read GitHub Actions docs; PR template guides',
    metadata: { week: 6, month: 2, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w6-3', course_id: 'se-realworld', track: 'plan', sort_order: 19, title: 'Set up GitHub Actions + create PR template + enforce lint',
    metadata: { week: 6, month: 2, hours: 22, kind: 'hands_on' } },

  { id: 'se-plan-w7-1', course_id: 'se-realworld', track: 'plan', sort_order: 20, title: 'OWASP API Top 10; secure coding',
    description: 'Audit API; add ownership checks + rate limiting.',
    metadata: { week: 7, month: 2, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w7-2', course_id: 'se-realworld', track: 'plan', sort_order: 21, title: 'Read OWASP cheat sheets; Zuplo API security guide',
    metadata: { week: 7, month: 2, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w7-3', course_id: 'se-realworld', track: 'plan', sort_order: 22, title: 'Audit API + add ownership checks + rate limiting',
    metadata: { week: 7, month: 2, hours: 22, kind: 'hands_on' } },

  { id: 'se-plan-w8-1', course_id: 'se-realworld', track: 'plan', sort_order: 23, title: 'Observability, SRE basics, runbooks',
    description: 'Add structured logging + alerts; write 2 runbooks.',
    metadata: { week: 8, month: 2, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w8-2', course_id: 'se-realworld', track: 'plan', sort_order: 24, title: 'Read Google SRE book intro; Better Stack docs',
    metadata: { week: 8, month: 2, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w8-3', course_id: 'se-realworld', track: 'plan', sort_order: 25, title: 'Add structured logging + alerts + write 2 runbooks',
    metadata: { week: 8, month: 2, hours: 22, kind: 'hands_on' } },

  // Month 3: Deployment, Scalability, and Client Engineering
  { id: 'se-plan-w9-1', course_id: 'se-realworld', track: 'plan', sort_order: 26, title: 'Deployment routes: PaaS, IaaS, containers',
    description: 'Dockerize API; run locally with Docker Compose.',
    metadata: { week: 9, month: 3, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w9-2', course_id: 'se-realworld', track: 'plan', sort_order: 27, title: 'Read Render/Railway/Fly.io docs; Docker Getting Started',
    metadata: { week: 9, month: 3, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w9-3', course_id: 'se-realworld', track: 'plan', sort_order: 28, title: 'Dockerize API + run locally with Docker Compose',
    metadata: { week: 9, month: 3, hours: 22, kind: 'hands_on' } },

  { id: 'se-plan-w10-1', course_id: 'se-realworld', track: 'plan', sort_order: 29, title: 'Caching, performance, scalability',
    description: 'Add Redis caching for read-heavy ERP endpoint.',
    metadata: { week: 10, month: 3, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w10-2', course_id: 'se-realworld', track: 'plan', sort_order: 30, title: 'Read caching strategy guides; watch System Design Interview videos',
    metadata: { week: 10, month: 3, hours: 22, kind: 'video' } },
  { id: 'se-plan-w10-3', course_id: 'se-realworld', track: 'plan', sort_order: 31, title: 'Add Redis caching for a read-heavy endpoint',
    metadata: { week: 10, month: 3, hours: 22, kind: 'hands_on' } },

  { id: 'se-plan-w11-1', course_id: 'se-realworld', track: 'plan', sort_order: 32, title: 'Client documentation, SLAs, change control',
    description: 'Write SOW template; define SLA for clients.',
    metadata: { week: 11, month: 3, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w11-2', course_id: 'se-realworld', track: 'plan', sort_order: 33, title: 'Read proposal/SOW templates; support playbook templates',
    metadata: { week: 11, month: 3, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w11-3', course_id: 'se-realworld', track: 'plan', sort_order: 34, title: 'Write SOW template + define SLA for clients',
    metadata: { week: 11, month: 3, hours: 22, kind: 'hands_on' } },

  { id: 'se-plan-w12-1', course_id: 'se-realworld', track: 'plan', sort_order: 35, title: 'Technical debt, long-term maintenance',
    description: 'Create debt inventory; allocate 20% of next sprint to debt.',
    metadata: { week: 12, month: 3, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w12-2', course_id: 'se-realworld', track: 'plan', sort_order: 36, title: 'Read technical debt OKR playbook',
    metadata: { week: 12, month: 3, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w12-3', course_id: 'se-realworld', track: 'plan', sort_order: 37, title: 'Create debt inventory + allocate 20% of next sprint to debt',
    metadata: { week: 12, month: 3, hours: 22, kind: 'hands_on' } },

  // ---- PROJECTS: 8 (guide §7) — each tagged with the topics it applies to (metadata.topics) ----
  { id: 'se-proj-1', course_id: 'se-realworld', track: 'project', sort_order: 1, title: 'Draw Your Architecture',
    description: 'Create C4 Context + Container diagrams; identify bounded contexts; write ADR-001 on the modular monolith.',
    metadata: { topics: ['se-topic-1', 'se-topic-2', 'se-topic-7'] } },
  { id: 'se-proj-2', course_id: 'se-realworld', track: 'project', sort_order: 2, title: 'Documentation Sprint',
    description: 'Write an SRS for the next ERP module; a BRD for one client engagement; an OpenAPI spec; publish with Swagger UI or Scalar.',
    metadata: { topics: ['se-topic-2', 'se-topic-3', 'se-topic-6'] } },
  { id: 'se-proj-3', course_id: 'se-realworld', track: 'project', sort_order: 3, title: 'Add Observability',
    description: 'Structured logging; connect to Better Stack/Logtail free tier; alerts for 5xx + high latency; two runbooks.',
    metadata: { topics: ['se-topic-5', 'se-topic-14'] } },
  { id: 'se-proj-4', course_id: 'se-realworld', track: 'project', sort_order: 4, title: 'Testing Ramp-Up',
    description: 'Jest unit tests for one core module; Supertest integration for auth + one business API; one Playwright E2E for login→dashboard; GitHub Actions on every PR.',
    metadata: { topics: ['se-topic-6', 'se-topic-13', 'se-topic-7'] } },
  { id: 'se-proj-5', course_id: 'se-realworld', track: 'project', sort_order: 5, title: 'Security Hardening',
    description: 'Audit API against OWASP API Top 10; per-resource ownership checks; rate limiting; run npm audit and triage.',
    metadata: { topics: ['se-topic-6', 'se-topic-14'] } },
  { id: 'se-proj-6', course_id: 'se-realworld', track: 'project', sort_order: 6, title: 'Database Optimization',
    description: 'Find the 5 slowest queries via Supabase logs/pg_stat_statements; add indexes and measure; document the strategy.',
    metadata: { topics: ['se-topic-6', 'se-topic-14'] } },
  { id: 'se-proj-7', course_id: 'se-realworld', track: 'project', sort_order: 7, title: 'Deployment Portability',
    description: 'Dockerize the Node.js API; run locally with Docker Compose including Postgres; document one-command full-stack local run.',
    metadata: { topics: ['se-topic-4', 'se-topic-7'] } },
  { id: 'se-proj-8', course_id: 'se-realworld', track: 'project', sort_order: 8, title: 'Evaluate New Hosting',
    description: 'Deploy a staging copy to Railway or Fly.io; compare cost, cold-start, deploy experience vs Render; write an ADR.',
    metadata: { topics: ['se-topic-4', 'se-topic-10'] } },

  // ---- TOPICS: 15 (guide §1..§15) — each with a description + an outline of the guide's ### sub-sections ----
  { id: 'se-topic-1', course_id: 'se-realworld', track: 'topic', sort_order: 1, title: 'System Architecture & Design Patterns',
    description: 'Architecture is the set of decisions that are expensive to reverse. This section covers the modular monolith, clean architecture, DDD, and VSA — the defaults that fit a 3-person ERP team.',
    metadata: { section: 1, subsections: 5, outline: [
      { id: 'se-topic-1.1', title: 'The Core Idea: Architecture = Expensive-to-Reverse Decisions', description: 'Architecture is the set of decisions expensive to reverse — system boundaries, data models, and dependency direction — not folder structure.' },
      { id: 'se-topic-1.2', title: 'Recommended Default: Modular Monolith + Clean Architecture', description: 'For a 3-person team, a modular monolith with strict internal modules is the default — simpler to deploy and easier to extract later.' },
      { id: 'se-topic-1.3', title: 'Three Architecture Styles to Combine', description: 'Combine Clean Architecture (inward dependencies), DDD (ubiquitous language + bounded contexts), and Vertical Slice Architecture (feature-first folders).' },
      { id: 'se-topic-1.4', title: 'Architecture Decision Framework', description: 'Start with a modular monolith; extract a service only when a module has a proven, independent reason to deploy or scale.' },
      { id: 'se-topic-1.5', title: 'Architecture for Your ERP This Week', description: 'Draw a C4 Context diagram, identify bounded contexts, and create one module per context with clearly defined interfaces.' },
    ] } },
  { id: 'se-topic-2', course_id: 'se-realworld', track: 'topic', sort_order: 2, title: 'Development (Technical) Documentation',
    description: 'The single source of truth for your team. Covers the documents every real project needs, plus practical SRS, ADR, OpenAPI, and C4 templates.',
    metadata: { section: 2, subsections: 5, outline: [
      { id: 'se-topic-2.1', title: 'Documents Every Real Project Needs', description: 'BRD, SRS, ADRs, SDD, OpenAPI, runbooks, README, and test plan — each with a distinct purpose and audience.' },
      { id: 'se-topic-2.2', title: 'SRS Template (Practical Version)', description: 'A practical outline for specifying what the system must do: functional and non-functional requirements, interfaces, and data.' },
      { id: 'se-topic-2.3', title: 'ADR Template', description: 'Every expensive-to-reverse decision gets an Architecture Decision Record: status, context, decision, consequences, alternatives.' },
      { id: 'se-topic-2.4', title: 'OpenAPI / API Documentation', description: 'Write an openapi.yaml as the contract; document every endpoint and keep the spec agreed between frontend and backend.' },
      { id: 'se-topic-2.5', title: 'C4 Model Diagrams', description: 'Communicate architecture at four zoom levels — context, container, component, code — using Structurizr, Mermaid, or Excalidraw.' },
    ] } },
  { id: 'se-topic-3', course_id: 'se-realworld', track: 'topic', sort_order: 3, title: 'Business & Client Documentation',
    description: 'Engineering docs help build it right; business docs help build the right thing. Covers BRD, user manuals, SOW, and SLA templates.',
    metadata: { section: 3, subsections: 4, outline: [
      { id: 'se-topic-3.1', title: 'BRD Template', description: 'Executive summary, scope, stakeholders, requirements, success metrics, timeline, risks, and approval.' },
      { id: 'se-topic-3.2', title: 'User Manual / Training Guide', description: 'Per module: what it does, who uses it, step-by-step workflows, common errors, and support contacts.' },
      { id: 'se-topic-3.3', title: 'Client Proposal / Statement of Work (SOW)', description: 'Scope, deliverables, timeline, cost, assumptions, change control, acceptance criteria, and support/maintenance.' },
      { id: 'se-topic-3.4', title: 'SLA Template (for Client Support)', description: 'Severity-based response and resolution targets, from P1 critical (15 min / 4 hr) to P4 low.' },
    ] } },
  { id: 'se-topic-4', course_id: 'se-realworld', track: 'topic', sort_order: 4, title: 'Tech Stack & Deployment Decision Framework',
    description: 'How to evaluate your current stack and choose where to host beyond Render. Covers framework, backend, and deployment-route decisions plus an environment strategy.',
    metadata: { section: 4, subsections: 6, outline: [
      { id: 'se-topic-4.1', title: 'Evaluating Your Current Stack', description: 'Vanilla JS + Node + Supabase + Render is a reasonable MVP start; know each layer’s role before changing it.' },
      { id: 'se-topic-4.2', title: 'When to Consider Changing Frontend Frameworks', description: 'Move to React or Vue when reusable components, state, and routing grow; migrate one isolated module first.' },
      { id: 'se-topic-4.3', title: 'When to Consider Changing Backend Approach', description: 'Add TypeScript first; consider typed languages only when strict transactional consistency or heavy CPU demands it.' },
      { id: 'se-topic-4.4', title: 'Deployment Route Options', description: 'PaaS, CaaS, IaaS, managed Kubernetes, serverless, and VPS — understand the menu and tradeoffs before choosing.' },
      { id: 'se-topic-4.5', title: 'Decision Framework for Hosting', description: 'Ask operational time, statefulness, region, compliance, traffic, HA, and budget in order; stay on Render until you hit real limits.' },
      { id: 'se-topic-4.6', title: 'Environment Strategy', description: 'Maintain development, staging, and production environments; never host production and staging on the same server or database.' },
    ] } },
  { id: 'se-topic-5', course_id: 'se-realworld', track: 'topic', sort_order: 5, title: 'Post-Deployment Support & SRE',
    description: 'Deployment is where the real responsibility starts. Covers observability, SLOs and error budgets, incident response, runbooks, toil reduction, and a production-readiness checklist.',
    metadata: { section: 5, subsections: 6, outline: [
      { id: 'se-topic-5.1', title: 'The Four Pillars of Observability', description: 'Metrics, logs, traces, and alerts — each tells you something different about system health.' },
      { id: 'se-topic-5.2', title: 'Define SLOs, SLIs, and Error Budgets', description: 'SLIs measure, SLOs set targets, SLAs promise contractually, and error budgets cap how much unreliability you can spend.' },
      { id: 'se-topic-5.3', title: 'Incident Response for Small Teams', description: 'Detect, triage, mitigate, resolve, postmortem — a blameless five-step loop with affordable tools.' },
      { id: 'se-topic-5.4', title: 'Runbook Template', description: 'Symptoms, immediate checks, mitigation, resolution, and escalation — documented so anyone can respond.' },
      { id: 'se-topic-5.5', title: 'Reducing Toil', description: 'Keep toil under 30% of operational time; automate backups, certs, dependency updates, and rollbacks.' },
      { id: 'se-topic-5.6', title: 'Production Readiness Checklist', description: 'Before a major release: monitoring, logs, backups, rollback, secrets, security scan, load test, runbooks, and client docs.' },
    ] } },
  { id: 'se-topic-6', course_id: 'se-realworld', track: 'topic', sort_order: 6, title: 'Engineering Discipline: Quality, Security, Maintainability',
    description: 'The habits that keep a growing system reliable: version control, code review, the testing pyramid, security (OWASP API Top 10), database design, technical debt, and CI/CD gates.',
    metadata: { section: 6, subsections: 8, outline: [
      { id: 'se-topic-6.1', title: 'Version Control and Branching', description: 'Use GitHub Flow or trunk-based development; GitFlow is usually overkill for a 3-person team.' },
      { id: 'se-topic-6.2', title: 'Code Review', description: 'Small PRs (under 400 lines), 4–24h turnaround, and a PR template: what changed, why, how to test.' },
      { id: 'se-topic-6.3', title: 'Testing Strategy: The Pyramid', description: '~70% unit, ~20% integration, ~10% E2E — buy the right confidence at the right cost.' },
      { id: 'se-topic-6.4', title: 'Contract Testing', description: 'Use Pact or validate against your OpenAPI spec on every PR so frontend and backend agree on the API shape.' },
      { id: 'se-topic-6.5', title: 'Security: OWASP Top 10 for APIs (2025/2026)', description: 'Priorities: BOLA/IDOR, broken auth, property-level auth, resource consumption, function-level auth, SSRF, misconfig, and supply chain.' },
      { id: 'se-topic-6.6', title: 'Database Design and Indexing', description: 'B-tree indexes on keys and filtered columns, composite indexes (equality then range), and expand-and-contract schema evolution.' },
      { id: 'se-topic-6.7', title: 'Technical Debt Management', description: 'Track debt in an inventory, rate by impact/effort, and allocate 15–20% of sprint capacity to paying it down.' },
      { id: 'se-topic-6.8', title: 'CI/CD and Quality Gates', description: 'Lint → scan → unit → integration → build → staging → smoke → approve → deploy, with rollback ready.' },
    ] } },
  { id: 'se-topic-7', course_id: 'se-realworld', track: 'topic', sort_order: 7, title: 'Hands-On Projects Applied to Your ERP',
    description: 'Eight projects that turn theory into applied skill on your ERP — from drawing architecture to evaluating new hosting.',
    metadata: { section: 7, subsections: 8, outline: [
      { id: 'se-topic-7.1', title: 'Project 1: Draw Your Architecture', description: 'Create C4 Context and Container diagrams; identify bounded contexts; write ADR-001 on the modular monolith.' },
      { id: 'se-topic-7.2', title: 'Project 2: Documentation Sprint', description: 'Write an SRS for the next module, a BRD for one client, an OpenAPI spec, and publish with Swagger UI or Scalar.' },
      { id: 'se-topic-7.3', title: 'Project 3: Add Observability', description: 'Structured logging; connect to Better Stack/Logtail free tier; alerts for 5xx + latency; two runbooks.' },
      { id: 'se-topic-7.4', title: 'Project 4: Testing Ramp-Up', description: 'Jest unit tests, Supertest integration for auth + one business API, one Playwright E2E, and GitHub Actions on every PR.' },
      { id: 'se-topic-7.5', title: 'Project 5: Security Hardening', description: 'Audit against OWASP API Top 10; per-resource ownership checks; rate limiting; npm audit and triage.' },
      { id: 'se-topic-7.6', title: 'Project 6: Database Optimization', description: 'Find the 5 slowest queries; add indexes and measure; document the indexing strategy.' },
      { id: 'se-topic-7.7', title: 'Project 7: Deployment Portability', description: 'Dockerize the Node.js API; run with Docker Compose + Postgres; document one-command local full-stack run.' },
      { id: 'se-topic-7.8', title: 'Project 8: Evaluate New Hosting', description: 'Deploy a staging copy to Railway or Fly.io; compare cost, cold-start, and deploy experience vs Render; write an ADR.' },
    ] } },
  { id: 'se-topic-8', course_id: 'se-realworld', track: 'topic', sort_order: 8, title: 'Weekly Study Plan',
    description: 'A 12-week plan (19–26 hrs/week) covering architecture and docs (Month 1), quality/security/operations (Month 2), and deployment/scalability/client engineering (Month 3).',
    metadata: { section: 8, subsections: 4, outline: [
      { id: 'se-topic-8.1', title: 'Month 1: Architecture, Documentation, and Database', description: 'C4/DDD basics, Clean Architecture/VSA, SRS/BRD/ADR writing, and database design/indexing — ~22 hrs/week.' },
      { id: 'se-topic-8.2', title: 'Month 2: Quality, Security, and Operations', description: 'Testing pyramid, CI/CD and code review, OWASP API Top 10, and observability/SRE — ~22 hrs/week.' },
      { id: 'se-topic-8.3', title: 'Month 3: Deployment, Scalability, and Client Engineering', description: 'Deployment routes, caching/performance, client docs/SLAs, and technical debt — ~22 hrs/week.' },
      { id: 'se-topic-8.4', title: 'Daily Rhythm Suggestion', description: 'Deep reading + hands-on blocks on no-class days; lighter review on class days; plan the next week on Sundays.' },
    ] } },
  { id: 'se-topic-9', course_id: 'se-realworld', track: 'topic', sort_order: 9, title: 'Recommended Resources',
    description: 'Curated books, video courses, official docs, articles, and tools from the guide — each tagged to the topics it covers.',
    metadata: { section: 9, subsections: 4, outline: [
      { id: 'se-topic-9.1', title: 'Books', description: 'Ten foundational books on architecture, design, data, DDD, production resilience, and trade-off analysis.' },
      { id: 'se-topic-9.2', title: 'Video Courses / Channels', description: 'ByteByteGo, ArjanCodes, Fireship, freeCodeCamp, and Udemy courses on architecture and system design.' },
      { id: 'se-topic-9.3', title: 'Official Documentation and Guides', description: 'C4, OpenAPI, OWASP, Google SRE, Docker, GitHub Actions, Jest, Playwright, Supabase, Render, Railway, Fly.io.' },
      { id: 'se-topic-9.4', title: 'Articles, Tutorials, and Tools', description: 'Rate limiting, testing taxonomies, SRS templates, branching strategies, and a tools table for the ERP.' },
    ] } },
  { id: 'se-topic-10', course_id: 'se-realworld', track: 'topic', sort_order: 10, title: 'Quick Reference: Decisions You Will Face Soon',
    description: 'Short answers to the recurring decisions: framework, microservices, hosting, TypeScript, testing volume, and technical debt.',
    metadata: { section: 10, subsections: 6, outline: [
      { id: 'se-topic-10.1', title: 'Should we move from vanilla JS to a framework?', description: 'Yes if the UI is growing or state is hard to manage; start with Vue or React in one isolated module.' },
      { id: 'se-topic-10.2', title: 'Should we split the monolith into microservices?', description: 'Not yet; extract a service only for independent deployment, scaling, or team ownership.' },
      { id: 'se-topic-10.3', title: 'Should we move off Render?', description: 'Evaluate Railway/Fly.io when Render limits hurt; move to a cloud only for VPCs, networking, or managed services.' },
      { id: 'se-topic-10.4', title: 'Should we add TypeScript?', description: 'Yes, as soon as possible — the highest-ROI change for a growing Node.js project.' },
      { id: 'se-topic-10.5', title: 'How much testing is enough?', description: 'Start with unit tests for core logic and integration tests for APIs; aim for meaningful coverage, not a number.' },
      { id: 'se-topic-10.6', title: 'How do we handle technical debt?', description: 'Track it, prioritize by impact/effort, and spend 15–20% of every sprint on it.' },
    ] } },
  { id: 'se-topic-11', course_id: 'se-realworld', track: 'topic', sort_order: 11, title: 'Conclusion: Your Path Forward',
    description: 'You are already running a software business. Pick one project per week, tie every concept to your ERP, write down decisions, and review them monthly.',
    metadata: { section: 11, subsections: 0 } },
  { id: 'se-topic-12', course_id: 'se-realworld', track: 'topic', sort_order: 12, title: 'Deep Dive: Software Design Patterns',
    description: 'Design patterns are a shared vocabulary, not rules. Covers creational, structural, behavioral, and architectural patterns plus anti-patterns and sources.',
    metadata: { section: 12, subsections: 7, outline: [
      { id: 'se-topic-12.1', title: 'Why Patterns Matter for Your ERP', description: 'Patterns reduce reinventing broken wheels: object creation, single instances, adding behavior, and adapting interfaces.' },
      { id: 'se-topic-12.2', title: 'Creational Patterns', description: 'Singleton, Factory, Abstract Factory, Builder, Prototype — dealing with object creation.' },
      { id: 'se-topic-12.3', title: 'Structural Patterns', description: 'Adapter, Bridge, Composite, Decorator, Facade, Flyweight, Proxy — how objects and classes compose.' },
      { id: 'se-topic-12.4', title: 'Behavioral Patterns', description: 'Chain of Responsibility, Command, Iterator, Mediator, Observer, State, Strategy, Template Method, Visitor — communication between objects.' },
      { id: 'se-topic-12.5', title: 'Architectural Patterns (Beyond GoF)', description: 'MVC/MVVM, Repository, Unit of Work, CQRS, Event Sourcing, Saga, Outbox — system-level patterns.' },
      { id: 'se-topic-12.6', title: 'Anti-Patterns to Avoid', description: 'God Object, Spaghetti Code, Golden Hammer, Premature Abstraction, Magic Numbers — and their better alternatives.' },
      { id: 'se-topic-12.7', title: 'Recommended Sources for Design Patterns', description: 'Refactoring Guru, Mosh Hamedani, SourceMaking, and Head First Design Patterns.' },
    ] } },
  { id: 'se-topic-13', course_id: 'se-realworld', track: 'topic', sort_order: 13, title: 'Deep Dive: Types of Software Testing',
    description: 'Testing is buying the right confidence at the right cost. Covers the pyramid, unit, integration, E2E, contract, performance, security, and a testing strategy for the ERP.',
    metadata: { section: 13, subsections: 10, outline: [
      { id: 'se-topic-13.1', title: 'The Testing Pyramid Expanded', description: '~70/20/10 unit/integration/E2E with cost and confidence per layer; the Testing Trophy favors static analysis + integration.' },
      { id: 'se-topic-13.2', title: 'Unit Testing', description: 'Test a single function/class in isolation — best for pure business logic, edge cases, and refactoring safety nets.' },
      { id: 'se-topic-13.3', title: 'Integration Testing', description: 'Test modules together with real DB/API calls — best for endpoint behavior and repository/service interaction.' },
      { id: 'se-topic-13.4', title: 'End-to-End (E2E) Testing', description: 'Drive the browser through complete workflows — best for critical user journeys; keep minimal and high-value.' },
      { id: 'se-topic-13.5', title: 'Contract Testing', description: 'Verify frontend and backend agree on the API contract — use Pact or validate against OpenAPI on every PR.' },
      { id: 'se-topic-13.6', title: 'Performance and Load Testing', description: 'Load, stress, spike, soak, endurance testing with k6, Artillery, JMeter — run before client go-lives and month-end peaks.' },
      { id: 'se-topic-13.7', title: 'Security Testing', description: 'SAST, DAST, SCA, penetration testing, and secrets scanning — layered tools for finding vulnerabilities.' },
      { id: 'se-topic-13.8', title: 'Other Important Test Types', description: 'Regression, smoke, usability, accessibility, mutation, and snapshot testing — each for a specific moment.' },
      { id: 'se-topic-13.9', title: 'Test Strategy for Your ERP', description: 'Static analysis first, then unit for business logic, integration for API+DB, E2E for critical flows, security scans in CI, and load tests before launches.' },
      { id: 'se-topic-13.10', title: 'Recommended Sources for Testing', description: 'Atlassian, Tricentis, Microsoft, CircleCI, Jest, Playwright, k6, OWASP ZAP, and Pact docs.' },
    ] } },
  { id: 'se-topic-14', course_id: 'se-realworld', track: 'topic', sort_order: 14, title: 'Deep Dive: Core Production Concepts',
    description: 'The small but essential concepts that separate a demo from a production system: rate limiting, caching, idempotency, pagination, background jobs, circuit breakers, and feature flags.',
    metadata: { section: 14, subsections: 7, outline: [
      { id: 'se-topic-14.1', title: 'Rate Limiting', description: 'Control request volume per time window with fixed window, sliding window, token bucket, or leaky bucket algorithms.' },
      { id: 'se-topic-14.2', title: 'Caching Strategies', description: 'Cache-Aside, Write-Through, Write-Behind, Refresh-Ahead — choose by staleness tolerance and freshness needs.' },
      { id: 'se-topic-14.3', title: 'Idempotency', description: 'An Idempotency-Key header makes retries and double-clicks safe — essential for invoices, charges, and payroll runs.' },
      { id: 'se-topic-14.4', title: 'Pagination', description: 'Never return unbounded lists — use cursor pagination for large sorted datasets, offset for small admin lists.' },
      { id: 'se-topic-14.5', title: 'Background Jobs', description: 'Move long or risky operations (reports, bulk email, imports, slow API calls) to queues with BullMQ, Agenda, or Supabase Edge Functions.' },
      { id: 'se-topic-14.6', title: 'Circuit Breakers', description: 'Stop calling a failing external service so the failure doesn’t cascade — closed, open, half-open states.' },
      { id: 'se-topic-14.7', title: 'Feature Flags', description: 'Deploy without exposing to users — gradual rollouts and quick rollbacks via LaunchDarkly, Flagsmith, or simple env vars.' },
    ] } },
  { id: 'se-topic-15', course_id: 'se-realworld', track: 'topic', sort_order: 15, title: 'Sources and References',
    description: 'The synthesized source categories behind this guide: architecture, design patterns, testing, security, databases, SRE, deployment, rate limiting, documentation, and code review.',
    metadata: { section: 15, subsections: 7, outline: [
      { id: 'se-topic-15.1', title: 'Architecture and Design', description: 'Richards & Ford, Clean Architecture, Domain-Driven Design, Jedrzejewski, VickyBytes, Wondel.ai.' },
      { id: 'se-topic-15.2', title: 'Design Patterns', description: 'Gamma et al. (GoF), Refactoring Guru, Mosh Hamedani, and the “8 Design Patterns” video.' },
      { id: 'se-topic-15.3', title: 'Testing', description: 'Cohn (testing pyramid), Atlassian, Tricentis, Microsoft, CircleCI, and Pact.' },
      { id: 'se-topic-15.4', title: 'Security', description: 'OWASP API Security Top 10, Zuplo, WorkOS, and Parasoft.' },
      { id: 'se-topic-15.5', title: 'Databases', description: 'Kleppmann, Nagurkar, JusDB, and Codelit indexing guides.' },
      { id: 'se-topic-15.6', title: 'SRE and Operations', description: 'Google SRE Book, Release It!, Better Stack, incident.io, and The Phoenix Project.' },
      { id: 'se-topic-15.7', title: 'Deployment and Infrastructure', description: 'Render, Railway, Fly.io, Docker, and Akuity GitOps guides.' },
    ] } },

  // ---- RESOURCES: guide §9 (books, videos, docs, articles) ----
  // Each resource is tagged with the topic id(s) it covers (metadata.topics), mapped from the guide.
  // Books (10) — each with a canonical url per Ruling #4
  { id: 'se-res-1', course_id: 'se-realworld', track: 'resource', sort_order: 1, title: 'A Philosophy of Software Design — Ousterhout', metadata: { type: 'book', author: 'John Ousterhout', url: 'https://www.amazon.com/Philosophy-Software-Design-John-Ousterhout/dp/1732902209', topics: ['se-topic-1', 'se-topic-6'] } },
  { id: 'se-res-2', course_id: 'se-realworld', track: 'resource', sort_order: 2, title: 'Clean Architecture — Robert C. Martin', metadata: { type: 'book', author: 'Robert C. Martin', url: 'https://www.amazon.com/Clean-Architecture-Craftsmans-Software-Structure/dp/0134494164', topics: ['se-topic-1', 'se-topic-12'], subtopics: ['se-topic-1.3', 'se-topic-12.5'] } },
  { id: 'se-res-3', course_id: 'se-realworld', track: 'resource', sort_order: 3, title: 'Designing Data-Intensive Applications — Kleppmann', metadata: { type: 'book', author: 'Martin Kleppmann', url: 'https://www.amazon.com/Designing-Data-Intensive-Applications-Reliable-Maintainable/dp/1449373321', topics: ['se-topic-6', 'se-topic-14'], subtopics: ['se-topic-6.6'] } },
  { id: 'se-res-4', course_id: 'se-realworld', track: 'resource', sort_order: 4, title: 'Domain-Driven Design — Eric Evans', metadata: { type: 'book', author: 'Eric Evans', url: 'https://www.amazon.com/Domain-Driven-Design-Tackling-Complexity-Software/dp/0321125215', topics: ['se-topic-1', 'se-topic-12'], subtopics: ['se-topic-1.3'] } },
  { id: 'se-res-5', course_id: 'se-realworld', track: 'resource', sort_order: 5, title: 'Release It! — Michael Nygard', metadata: { type: 'book', author: 'Michael Nygard', url: 'https://www.oreilly.com/library/view/release-it-2nd/9781680505264/', topics: ['se-topic-5', 'se-topic-14'], subtopics: ['se-topic-14.6'] } },
  { id: 'se-res-6', course_id: 'se-realworld', track: 'resource', sort_order: 6, title: 'The Phoenix Project / The Unicorn Project — Gene Kim', metadata: { type: 'book', author: 'Gene Kim', url: 'https://www.amazon.com/Phoenix-Project-DevOps-Helping-Business/dp/1942788290', topics: ['se-topic-6', 'se-topic-5'] } },
  { id: 'se-res-7', course_id: 'se-realworld', track: 'resource', sort_order: 7, title: 'Building Microservices — Sam Newman', metadata: { type: 'book', author: 'Sam Newman', url: 'https://www.oreilly.com/library/view/building-microservices-2nd/9781492034025/', topics: ['se-topic-1', 'se-topic-4'], subtopics: ['se-topic-1.4'] } },
  { id: 'se-res-8', course_id: 'se-realworld', track: 'resource', sort_order: 8, title: 'Software Architecture: The Hard Parts — Neal Ford et al.', metadata: { type: 'book', author: 'Neal Ford', url: 'https://www.oreilly.com/library/view/software-architecture/9781492085296/', topics: ['se-topic-1', 'se-topic-10', 'se-topic-4'], subtopics: ['se-topic-1.4', 'se-topic-10.2'] } },
  { id: 'se-res-9', course_id: 'se-realworld', track: 'resource', sort_order: 9, title: 'Fundamentals of Software Architecture, 2nd Ed. — Richards & Ford', metadata: { type: 'book', author: 'Mark Richards & Neal Ford', url: 'https://www.oreilly.com/library/view/fundamentals-of-software/9781098114721/', topics: ['se-topic-1', 'se-topic-12'] } },
  { id: 'se-res-10', course_id: 'se-realworld', track: 'resource', sort_order: 10, title: 'Head First Design Patterns, 2nd Ed.', metadata: { type: 'book', url: 'https://www.amazon.com/Head-First-Design-Patterns-Brain-Friendly/dp/149207800X', topics: ['se-topic-1', 'se-topic-12'] } },
  // Video courses (10) — urls from guide §9
  { id: 'se-res-11', course_id: 'se-realworld', track: 'resource', sort_order: 11, title: 'ByteByteGo (system design)', metadata: { type: 'video', url: 'https://www.youtube.com/@ByteByteGo', topics: ['se-topic-1', 'se-topic-4', 'se-topic-14'] } },
  { id: 'se-res-12', course_id: 'se-realworld', track: 'resource', sort_order: 12, title: 'ArjanCodes', metadata: { type: 'video', url: 'https://www.youtube.com/@ArjanCodes', topics: ['se-topic-1', 'se-topic-12', 'se-topic-6'] } },
  { id: 'se-res-13', course_id: 'se-realworld', track: 'resource', sort_order: 13, title: 'Fireship', metadata: { type: 'video', url: 'https://www.youtube.com/@Fireship', topics: ['se-topic-4', 'se-topic-10'] } },
  { id: 'se-res-14', course_id: 'se-realworld', track: 'resource', sort_order: 14, title: 'Traversy Media', metadata: { type: 'video', url: 'https://www.youtube.com/@TraversyMedia', topics: ['se-topic-7', 'se-topic-4'] } },
  { id: 'se-res-15', course_id: 'se-realworld', track: 'resource', sort_order: 15, title: 'freeCodeCamp', metadata: { type: 'video', url: 'https://www.youtube.com/@freecodecamp', topics: ['se-topic-6', 'se-topic-13', 'se-topic-4'] } },
  { id: 'se-res-16', course_id: 'se-realworld', track: 'resource', sort_order: 16, title: 'Design Patterns in Plain English — Mosh Hamedani', metadata: { type: 'video', url: 'https://www.youtube.com/watch?v=NU_1StN5Tkk', topics: ['se-topic-1', 'se-topic-12'], subtopics: ['se-topic-12.7'] } },
  { id: 'se-res-17', course_id: 'se-realworld', track: 'resource', sort_order: 17, title: '8 Design Patterns EVERY Developer Should Know', metadata: { type: 'video', url: 'https://www.youtube.com/watch?v=tAuRQs_d9F8', topics: ['se-topic-1', 'se-topic-12'], subtopics: ['se-topic-12.7'] } },
  { id: 'se-res-18', course_id: 'se-realworld', track: 'resource', sort_order: 18, title: 'Master Software Architecture (GOTO 2025)', metadata: { type: 'video', url: 'https://www.youtube.com/watch?v=ZCrCqbblXjk', topics: ['se-topic-1', 'se-topic-12'] } },
  { id: 'se-res-19', course_id: 'se-realworld', track: 'resource', sort_order: 19, title: 'Udemy: Software Architecture & Design of Modern Large Scale Systems', metadata: { type: 'video', url: 'https://www.udemy.com/course/software-architecture-design-of-modern-large-scale-systems/', topics: ['se-topic-1', 'se-topic-4'] } },
  { id: 'se-res-20', course_id: 'se-realworld', track: 'resource', sort_order: 20, title: 'Udemy: Modern Software Architecture - Foundation', metadata: { type: 'video', url: 'https://www.udemy.com/course/modern-software-architecture-foundation/', topics: ['se-topic-1', 'se-topic-4'] } },
  // Docs (12)
  { id: 'se-res-21', course_id: 'se-realworld', track: 'resource', sort_order: 21, title: 'C4 Model', metadata: { type: 'doc', url: 'https://c4model.com/', topics: ['se-topic-1', 'se-topic-2', 'se-topic-7'], subtopics: ['se-topic-2.5'] } },
  { id: 'se-res-22', course_id: 'se-realworld', track: 'resource', sort_order: 22, title: 'OpenAPI Specification', metadata: { type: 'doc', url: 'https://swagger.io/specification/', topics: ['se-topic-2', 'se-topic-6'], subtopics: ['se-topic-2.4'] } },
  { id: 'se-res-23', course_id: 'se-realworld', track: 'resource', sort_order: 23, title: 'OWASP API Security Top 10', metadata: { type: 'doc', url: 'https://owasp.org/www-project-api-security/', topics: ['se-topic-6', 'se-topic-7'], subtopics: ['se-topic-6.5'] } },
  { id: 'se-res-24', course_id: 'se-realworld', track: 'resource', sort_order: 24, title: 'Google SRE Book', metadata: { type: 'doc', url: 'https://sre.google/sre-book/table-of-contents/', topics: ['se-topic-5', 'se-topic-14'] } },
  { id: 'se-res-25', course_id: 'se-realworld', track: 'resource', sort_order: 25, title: 'Docker Getting Started', metadata: { type: 'doc', url: 'https://docs.docker.com/get-started/', topics: ['se-topic-4', 'se-topic-7'], subtopics: ['se-topic-4.4'] } },
  { id: 'se-res-26', course_id: 'se-realworld', track: 'resource', sort_order: 26, title: 'GitHub Actions Documentation', metadata: { type: 'doc', url: 'https://docs.github.com/en/actions', topics: ['se-topic-6', 'se-topic-7'], subtopics: ['se-topic-6.8'] } },
  { id: 'se-res-27', course_id: 'se-realworld', track: 'resource', sort_order: 27, title: 'Jest Documentation', metadata: { type: 'doc', url: 'https://jestjs.io/docs/getting-started', topics: ['se-topic-6', 'se-topic-13'], subtopics: ['se-topic-13.2'] } },
  { id: 'se-res-28', course_id: 'se-realworld', track: 'resource', sort_order: 28, title: 'Playwright Documentation', metadata: { type: 'doc', url: 'https://playwright.dev/docs/intro', topics: ['se-topic-6', 'se-topic-13', 'se-topic-7'], subtopics: ['se-topic-13.4'] } },
  { id: 'se-res-29', course_id: 'se-realworld', track: 'resource', sort_order: 29, title: 'Supabase Documentation', metadata: { type: 'doc', url: 'https://supabase.com/docs', topics: ['se-topic-4', 'se-topic-10'] } },
  { id: 'se-res-30', course_id: 'se-realworld', track: 'resource', sort_order: 30, title: 'Render Documentation', metadata: { type: 'doc', url: 'https://docs.render.com/', topics: ['se-topic-4', 'se-topic-7'] } },
  { id: 'se-res-31', course_id: 'se-realworld', track: 'resource', sort_order: 31, title: 'Railway Documentation', metadata: { type: 'doc', url: 'https://docs.railway.app/', topics: ['se-topic-4', 'se-topic-7'] } },
  { id: 'se-res-32', course_id: 'se-realworld', track: 'resource', sort_order: 32, title: 'Fly.io Documentation', metadata: { type: 'doc', url: 'https://fly.io/docs/', topics: ['se-topic-4', 'se-topic-7'] } },
  // Articles (7) + 1 doc
  { id: 'se-res-33', course_id: 'se-realworld', track: 'resource', sort_order: 33, title: 'Designing a Rate Limiter: 4 Algorithms, Real Trade-Offs', metadata: { type: 'article', url: 'https://dev.to/gabrielanhaia/designing-a-rate-limiter-4-algorithms-real-trade-offs-3h5', topics: ['se-topic-6', 'se-topic-7', 'se-topic-14'], subtopics: ['se-topic-14.1'] } },
  { id: 'se-res-34', course_id: 'se-realworld', track: 'resource', sort_order: 34, title: 'How API Rate Limiting Works', metadata: { type: 'article', url: 'https://mohamed-hendawy.medium.com/how-api-rate-limiting-works-fixed-window-token-bucket-sliding-window-explained-c16521f3e0e6', topics: ['se-topic-6', 'se-topic-7', 'se-topic-14'], subtopics: ['se-topic-14.1'] } },
  { id: 'se-res-35', course_id: 'se-realworld', track: 'resource', sort_order: 35, title: 'The different types of testing in software (Atlassian)', metadata: { type: 'article', url: 'https://www.atlassian.com/continuous-delivery/software-testing/types-of-software-testing', topics: ['se-topic-6', 'se-topic-13'], subtopics: ['se-topic-13.10'] } },
  { id: 'se-res-36', course_id: 'se-realworld', track: 'resource', sort_order: 36, title: 'Types of software testing (Tricentis)', metadata: { type: 'article', url: 'https://www.tricentis.com/learn/software-testing-types', topics: ['se-topic-6', 'se-topic-13'], subtopics: ['se-topic-13.10'] } },
  { id: 'se-res-37', course_id: 'se-realworld', track: 'resource', sort_order: 37, title: 'Unit vs Integration vs System vs E2E Testing (Microsoft)', metadata: { type: 'article', url: 'https://microsoft.github.io/code-with-engineering-playbook/automated-testing/e2e-testing/testing-comparison/', topics: ['se-topic-6', 'se-topic-13'], subtopics: ['se-topic-13.10'] } },
  { id: 'se-res-38', course_id: 'se-realworld', track: 'resource', sort_order: 38, title: 'Software requirement document template (Asana)', metadata: { type: 'article', url: 'https://asana.com/resources/software-requirement-document-template', topics: ['se-topic-2', 'se-topic-3'], subtopics: ['se-topic-2.2'] } },
  { id: 'se-res-39', course_id: 'se-realworld', track: 'resource', sort_order: 39, title: 'Trunk-Based Development vs. Gitflow (Flagsmith)', metadata: { type: 'article', url: 'https://www.flagsmith.com/blog/trunk-based-development-vs-gitflow', topics: ['se-topic-6'], subtopics: ['se-topic-6.1'] } },
  { id: 'se-res-40', course_id: 'se-realworld', track: 'resource', sort_order: 40, title: 'Refactoring Guru — Design Patterns', metadata: { type: 'doc', url: 'https://refactoring.guru/design-patterns', topics: ['se-topic-1', 'se-topic-12'], subtopics: ['se-topic-12.7'] } },
];

import type { Course } from './types';

export const SEED_COURSE: Course = {
  id: 'se-realworld',
  title: 'Software Engineering — Real-World Study Guide',
  description: 'A tailored 12-week software engineering course.',
  emoji: '🛠️',
  owner_user_id: null,
  is_seed: true,
  notebook_url: 'https://notebooklm.google.com/notebook/31e6db8c-9b66-4e80-8e4f-b643ac7082db',
  created_at: '2026-08-15T00:00:00Z',
};
