import type { Item } from './types';

export const SEED_ITEMS: Item[] = [
  // ---- PLAN: 12 weeks (guide §8) ----
  // Month 1: Architecture, Documentation, and Database
  { id: 'se-plan-w1-1', track: 'plan', sort_order: 1, title: 'Architecture patterns, C4, DDD basics',
    description: 'Draw C4 diagrams for the ERP; write ADR-001.',
    metadata: { week: 1, month: 1, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w1-2', track: 'plan', sort_order: 2, title: 'Read A Philosophy of Software Design (Ousterhout)',
    metadata: { week: 1, month: 1, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w1-3', track: 'plan', sort_order: 3, title: 'C4 model docs (reading)',
    metadata: { week: 1, month: 1, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w1-4', track: 'plan', sort_order: 4, title: 'Draw C4 diagrams + write ADR-001',
    metadata: { week: 1, month: 1, hours: 22, kind: 'hands_on' } },

  { id: 'se-plan-w2-1', track: 'plan', sort_order: 5, title: 'Clean Architecture, VSA, modular monolith',
    description: 'Refactor one ERP module into clean layers.',
    metadata: { week: 2, month: 1, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w2-2', track: 'plan', sort_order: 6, title: 'Read Clean Architecture (Martin) ch1-10; VickyBytes architecture roadmap',
    metadata: { week: 2, month: 1, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w2-3', track: 'plan', sort_order: 7, title: 'Refactor one ERP module into clean layers',
    metadata: { week: 2, month: 1, hours: 22, kind: 'hands_on' } },

  { id: 'se-plan-w3-1', track: 'plan', sort_order: 8, title: 'SRS/BRD/ADR writing; API documentation',
    description: 'Write SRS for next module; publish OpenAPI spec.',
    metadata: { week: 3, month: 1, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w3-2', track: 'plan', sort_order: 9, title: 'Read Asana SRS guide; OpenAPI docs',
    metadata: { week: 3, month: 1, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w3-3', track: 'plan', sort_order: 10, title: 'Write SRS for next module + publish OpenAPI spec',
    metadata: { week: 3, month: 1, hours: 22, kind: 'hands_on' } },

  { id: 'se-plan-w4-1', track: 'plan', sort_order: 11, title: 'Database design, indexing, schema evolution',
    description: 'Audit slow queries; add 3 indexes; document strategy.',
    metadata: { week: 4, month: 1, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w4-2', track: 'plan', sort_order: 12, title: 'Read Designing Data-Intensive Applications (Kleppmann) ch2-3; Postgres indexing guides',
    metadata: { week: 4, month: 1, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w4-3', track: 'plan', sort_order: 13, title: 'Audit slow queries + add 3 indexes + document strategy',
    metadata: { week: 4, month: 1, hours: 22, kind: 'hands_on' } },

  // Month 2: Quality, Security, and Operations
  { id: 'se-plan-w5-1', track: 'plan', sort_order: 14, title: 'Testing pyramid; unit and integration tests',
    description: 'Add Jest unit tests + Supertest integration tests.',
    metadata: { week: 5, month: 2, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w5-2', track: 'plan', sort_order: 15, title: 'Read CircleCI testing pyramid guide; Jest docs',
    metadata: { week: 5, month: 2, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w5-3', track: 'plan', sort_order: 16, title: 'Add Jest unit tests + Supertest integration tests',
    metadata: { week: 5, month: 2, hours: 22, kind: 'hands_on' } },

  { id: 'se-plan-w6-1', track: 'plan', sort_order: 17, title: 'CI/CD, quality gates, code review',
    description: 'Set up GitHub Actions; create PR template; enforce lint.',
    metadata: { week: 6, month: 2, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w6-2', track: 'plan', sort_order: 18, title: 'Read GitHub Actions docs; PR template guides',
    metadata: { week: 6, month: 2, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w6-3', track: 'plan', sort_order: 19, title: 'Set up GitHub Actions + create PR template + enforce lint',
    metadata: { week: 6, month: 2, hours: 22, kind: 'hands_on' } },

  { id: 'se-plan-w7-1', track: 'plan', sort_order: 20, title: 'OWASP API Top 10; secure coding',
    description: 'Audit API; add ownership checks + rate limiting.',
    metadata: { week: 7, month: 2, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w7-2', track: 'plan', sort_order: 21, title: 'Read OWASP cheat sheets; Zuplo API security guide',
    metadata: { week: 7, month: 2, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w7-3', track: 'plan', sort_order: 22, title: 'Audit API + add ownership checks + rate limiting',
    metadata: { week: 7, month: 2, hours: 22, kind: 'hands_on' } },

  { id: 'se-plan-w8-1', track: 'plan', sort_order: 23, title: 'Observability, SRE basics, runbooks',
    description: 'Add structured logging + alerts; write 2 runbooks.',
    metadata: { week: 8, month: 2, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w8-2', track: 'plan', sort_order: 24, title: 'Read Google SRE book intro; Better Stack docs',
    metadata: { week: 8, month: 2, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w8-3', track: 'plan', sort_order: 25, title: 'Add structured logging + alerts + write 2 runbooks',
    metadata: { week: 8, month: 2, hours: 22, kind: 'hands_on' } },

  // Month 3: Deployment, Scalability, and Client Engineering
  { id: 'se-plan-w9-1', track: 'plan', sort_order: 26, title: 'Deployment routes: PaaS, IaaS, containers',
    description: 'Dockerize API; run locally with Docker Compose.',
    metadata: { week: 9, month: 3, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w9-2', track: 'plan', sort_order: 27, title: 'Read Render/Railway/Fly.io docs; Docker Getting Started',
    metadata: { week: 9, month: 3, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w9-3', track: 'plan', sort_order: 28, title: 'Dockerize API + run locally with Docker Compose',
    metadata: { week: 9, month: 3, hours: 22, kind: 'hands_on' } },

  { id: 'se-plan-w10-1', track: 'plan', sort_order: 29, title: 'Caching, performance, scalability',
    description: 'Add Redis caching for read-heavy ERP endpoint.',
    metadata: { week: 10, month: 3, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w10-2', track: 'plan', sort_order: 30, title: 'Read caching strategy guides; watch System Design Interview videos',
    metadata: { week: 10, month: 3, hours: 22, kind: 'video' } },
  { id: 'se-plan-w10-3', track: 'plan', sort_order: 31, title: 'Add Redis caching for a read-heavy endpoint',
    metadata: { week: 10, month: 3, hours: 22, kind: 'hands_on' } },

  { id: 'se-plan-w11-1', track: 'plan', sort_order: 32, title: 'Client documentation, SLAs, change control',
    description: 'Write SOW template; define SLA for clients.',
    metadata: { week: 11, month: 3, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w11-2', track: 'plan', sort_order: 33, title: 'Read proposal/SOW templates; support playbook templates',
    metadata: { week: 11, month: 3, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w11-3', track: 'plan', sort_order: 34, title: 'Write SOW template + define SLA for clients',
    metadata: { week: 11, month: 3, hours: 22, kind: 'hands_on' } },

  { id: 'se-plan-w12-1', track: 'plan', sort_order: 35, title: 'Technical debt, long-term maintenance',
    description: 'Create debt inventory; allocate 20% of next sprint to debt.',
    metadata: { week: 12, month: 3, hours: 22, kind: 'focus' } },
  { id: 'se-plan-w12-2', track: 'plan', sort_order: 36, title: 'Read technical debt OKR playbook',
    metadata: { week: 12, month: 3, hours: 22, kind: 'reading' } },
  { id: 'se-plan-w12-3', track: 'plan', sort_order: 37, title: 'Create debt inventory + allocate 20% of next sprint to debt',
    metadata: { week: 12, month: 3, hours: 22, kind: 'hands_on' } },

  // ---- PROJECTS: 8 (guide §7) ----
  { id: 'se-proj-1', track: 'project', sort_order: 1, title: 'Draw Your Architecture',
    description: 'Create C4 Context + Container diagrams; identify bounded contexts; write ADR-001 on the modular monolith.',
    metadata: {} },
  { id: 'se-proj-2', track: 'project', sort_order: 2, title: 'Documentation Sprint',
    description: 'Write an SRS for the next ERP module; a BRD for one client engagement; an OpenAPI spec; publish with Swagger UI or Scalar.',
    metadata: {} },
  { id: 'se-proj-3', track: 'project', sort_order: 3, title: 'Add Observability',
    description: 'Structured logging; connect to Better Stack/Logtail free tier; alerts for 5xx + high latency; two runbooks.',
    metadata: {} },
  { id: 'se-proj-4', track: 'project', sort_order: 4, title: 'Testing Ramp-Up',
    description: 'Jest unit tests for one core module; Supertest integration for auth + one business API; one Playwright E2E for login→dashboard; GitHub Actions on every PR.',
    metadata: {} },
  { id: 'se-proj-5', track: 'project', sort_order: 5, title: 'Security Hardening',
    description: 'Audit API against OWASP API Top 10; per-resource ownership checks; rate limiting; run npm audit and triage.',
    metadata: {} },
  { id: 'se-proj-6', track: 'project', sort_order: 6, title: 'Database Optimization',
    description: 'Find the 5 slowest queries via Supabase logs/pg_stat_statements; add indexes and measure; document the strategy.',
    metadata: {} },
  { id: 'se-proj-7', track: 'project', sort_order: 7, title: 'Deployment Portability',
    description: 'Dockerize the Node.js API; run locally with Docker Compose including Postgres; document one-command full-stack local run.',
    metadata: {} },
  { id: 'se-proj-8', track: 'project', sort_order: 8, title: 'Evaluate New Hosting',
    description: 'Deploy a staging copy to Railway or Fly.io; compare cost, cold-start, deploy experience vs Render; write an ADR.',
    metadata: {} },

  // ---- TOPICS: 15 (guide §1..§15) ----
  { id: 'se-topic-1', track: 'topic', sort_order: 1, title: 'System Architecture & Design Patterns', metadata: { section: 1, subsections: 5 } },
  { id: 'se-topic-2', track: 'topic', sort_order: 2, title: 'Development (Technical) Documentation', metadata: { section: 2, subsections: 5 } },
  { id: 'se-topic-3', track: 'topic', sort_order: 3, title: 'Business & Client Documentation', metadata: { section: 3, subsections: 4 } },
  { id: 'se-topic-4', track: 'topic', sort_order: 4, title: 'Tech Stack & Deployment Decision Framework', metadata: { section: 4, subsections: 6 } },
  { id: 'se-topic-5', track: 'topic', sort_order: 5, title: 'Post-Deployment Support & SRE', metadata: { section: 5, subsections: 6 } },
  { id: 'se-topic-6', track: 'topic', sort_order: 6, title: 'Engineering Discipline: Quality, Security, Maintainability', metadata: { section: 6, subsections: 8 } },
  { id: 'se-topic-7', track: 'topic', sort_order: 7, title: 'Hands-On Projects Applied to Your ERP', metadata: { section: 7, subsections: 8 } },
  { id: 'se-topic-8', track: 'topic', sort_order: 8, title: 'Weekly Study Plan', metadata: { section: 8, subsections: 4 } },
  { id: 'se-topic-9', track: 'topic', sort_order: 9, title: 'Recommended Resources', metadata: { section: 9, subsections: 4 } },
  { id: 'se-topic-10', track: 'topic', sort_order: 10, title: 'Quick Reference: Decisions You Will Face Soon', metadata: { section: 10, subsections: 6 } },
  { id: 'se-topic-11', track: 'topic', sort_order: 11, title: 'Conclusion: Your Path Forward', metadata: { section: 11, subsections: 0 } },
  { id: 'se-topic-12', track: 'topic', sort_order: 12, title: 'Deep Dive: Software Design Patterns', metadata: { section: 12, subsections: 7 } },
  { id: 'se-topic-13', track: 'topic', sort_order: 13, title: 'Deep Dive: Types of Software Testing', metadata: { section: 13, subsections: 10 } },
  { id: 'se-topic-14', track: 'topic', sort_order: 14, title: 'Deep Dive: Core Production Concepts', metadata: { section: 14, subsections: 7 } },
  { id: 'se-topic-15', track: 'topic', sort_order: 15, title: 'Sources and References', metadata: { section: 15, subsections: 7 } },

  // ---- RESOURCES: guide §9 (books, videos, docs, articles) ----
  // Each resource is tagged with the topic id(s) it covers (metadata.topics), mapped from the guide.
  // Books (10) — each with a canonical url per Ruling #4
  { id: 'se-res-1', track: 'resource', sort_order: 1, title: 'A Philosophy of Software Design — Ousterhout', metadata: { type: 'book', author: 'John Ousterhout', url: 'https://www.amazon.com/Philosophy-Software-Design-John-Ousterhout/dp/1732902209', topics: ['se-topic-1', 'se-topic-12', 'se-topic-6'] } },
  { id: 'se-res-2', track: 'resource', sort_order: 2, title: 'Clean Architecture — Robert C. Martin', metadata: { type: 'book', author: 'Robert C. Martin', url: 'https://www.amazon.com/Clean-Architecture-Craftsmans-Software-Structure/dp/0134494164', topics: ['se-topic-1', 'se-topic-12'] } },
  { id: 'se-res-3', track: 'resource', sort_order: 3, title: 'Designing Data-Intensive Applications — Kleppmann', metadata: { type: 'book', author: 'Martin Kleppmann', url: 'https://www.amazon.com/Designing-Data-Intensive-Applications-Reliable-Maintainable/dp/1449373321', topics: ['se-topic-6', 'se-topic-14', 'se-topic-1'] } },
  { id: 'se-res-4', track: 'resource', sort_order: 4, title: 'Domain-Driven Design — Eric Evans', metadata: { type: 'book', author: 'Eric Evans', url: 'https://www.amazon.com/Domain-Driven-Design-Tackling-Complexity-Software/dp/0321125215', topics: ['se-topic-1', 'se-topic-12'] } },
  { id: 'se-res-5', track: 'resource', sort_order: 5, title: 'Release It! — Michael Nygard', metadata: { type: 'book', author: 'Michael Nygard', url: 'https://www.oreilly.com/library/view/release-it-2nd/9781680505264/', topics: ['se-topic-5', 'se-topic-14'] } },
  { id: 'se-res-6', track: 'resource', sort_order: 6, title: 'The Phoenix Project / The Unicorn Project — Gene Kim', metadata: { type: 'book', author: 'Gene Kim', url: 'https://www.amazon.com/Phoenix-Project-DevOps-Helping-Business/dp/1942788290', topics: ['se-topic-6', 'se-topic-5'] } },
  { id: 'se-res-7', track: 'resource', sort_order: 7, title: 'Building Microservices — Sam Newman', metadata: { type: 'book', author: 'Sam Newman', url: 'https://www.oreilly.com/library/view/building-microservices-2nd/9781492034025/', topics: ['se-topic-1', 'se-topic-4'] } },
  { id: 'se-res-8', track: 'resource', sort_order: 8, title: 'Software Architecture: The Hard Parts — Neal Ford et al.', metadata: { type: 'book', author: 'Neal Ford', url: 'https://www.oreilly.com/library/view/software-architecture/9781492085296/', topics: ['se-topic-1', 'se-topic-10', 'se-topic-4'] } },
  { id: 'se-res-9', track: 'resource', sort_order: 9, title: 'Fundamentals of Software Architecture, 2nd Ed. — Richards & Ford', metadata: { type: 'book', author: 'Mark Richards & Neal Ford', url: 'https://www.oreilly.com/library/view/fundamentals-of-software/9781098114721/', topics: ['se-topic-1', 'se-topic-12'] } },
  { id: 'se-res-10', track: 'resource', sort_order: 10, title: 'Head First Design Patterns, 2nd Ed.', metadata: { type: 'book', url: 'https://www.amazon.com/Head-First-Design-Patterns-Brain-Friendly/dp/149207800X', topics: ['se-topic-1', 'se-topic-12'] } },
  // Video courses (10) — urls from guide §9
  { id: 'se-res-11', track: 'resource', sort_order: 11, title: 'ByteByteGo (system design)', metadata: { type: 'video', url: 'https://www.youtube.com/@ByteByteGo', topics: ['se-topic-1', 'se-topic-4', 'se-topic-14'] } },
  { id: 'se-res-12', track: 'resource', sort_order: 12, title: 'ArjanCodes', metadata: { type: 'video', url: 'https://www.youtube.com/@ArjanCodes', topics: ['se-topic-1', 'se-topic-12', 'se-topic-6'] } },
  { id: 'se-res-13', track: 'resource', sort_order: 13, title: 'Fireship', metadata: { type: 'video', url: 'https://www.youtube.com/@Fireship', topics: ['se-topic-4', 'se-topic-10'] } },
  { id: 'se-res-14', track: 'resource', sort_order: 14, title: 'Traversy Media', metadata: { type: 'video', url: 'https://www.youtube.com/@TraversyMedia', topics: ['se-topic-7', 'se-topic-4'] } },
  { id: 'se-res-15', track: 'resource', sort_order: 15, title: 'freeCodeCamp', metadata: { type: 'video', url: 'https://www.youtube.com/@freecodecamp', topics: ['se-topic-6', 'se-topic-13', 'se-topic-4'] } },
  { id: 'se-res-16', track: 'resource', sort_order: 16, title: 'Design Patterns in Plain English — Mosh Hamedani', metadata: { type: 'video', url: 'https://www.youtube.com/watch?v=NU_1StN5Tkk', topics: ['se-topic-1', 'se-topic-12'] } },
  { id: 'se-res-17', track: 'resource', sort_order: 17, title: '8 Design Patterns EVERY Developer Should Know', metadata: { type: 'video', url: 'https://www.youtube.com/watch?v=tAuRQs_d9F8', topics: ['se-topic-1', 'se-topic-12'] } },
  { id: 'se-res-18', track: 'resource', sort_order: 18, title: 'Master Software Architecture (GOTO 2025)', metadata: { type: 'video', url: 'https://www.youtube.com/watch?v=ZCrCqbblXjk', topics: ['se-topic-1', 'se-topic-12'] } },
  { id: 'se-res-19', track: 'resource', sort_order: 19, title: 'Udemy: Software Architecture & Design of Modern Large Scale Systems', metadata: { type: 'video', url: 'https://www.udemy.com/course/software-architecture-design-of-modern-large-scale-systems/', topics: ['se-topic-1', 'se-topic-4'] } },
  { id: 'se-res-20', track: 'resource', sort_order: 20, title: 'Udemy: Modern Software Architecture - Foundation', metadata: { type: 'video', url: 'https://www.udemy.com/course/modern-software-architecture-foundation/', topics: ['se-topic-1', 'se-topic-4'] } },
  // Docs (12)
  { id: 'se-res-21', track: 'resource', sort_order: 21, title: 'C4 Model', metadata: { type: 'doc', url: 'https://c4model.com/', topics: ['se-topic-1', 'se-topic-2', 'se-topic-7'] } },
  { id: 'se-res-22', track: 'resource', sort_order: 22, title: 'OpenAPI Specification', metadata: { type: 'doc', url: 'https://swagger.io/specification/', topics: ['se-topic-2', 'se-topic-6'] } },
  { id: 'se-res-23', track: 'resource', sort_order: 23, title: 'OWASP API Security Top 10', metadata: { type: 'doc', url: 'https://owasp.org/www-project-api-security/', topics: ['se-topic-6', 'se-topic-7'] } },
  { id: 'se-res-24', track: 'resource', sort_order: 24, title: 'Google SRE Book', metadata: { type: 'doc', url: 'https://sre.google/sre-book/table-of-contents/', topics: ['se-topic-5', 'se-topic-14'] } },
  { id: 'se-res-25', track: 'resource', sort_order: 25, title: 'Docker Getting Started', metadata: { type: 'doc', url: 'https://docs.docker.com/get-started/', topics: ['se-topic-4', 'se-topic-7'] } },
  { id: 'se-res-26', track: 'resource', sort_order: 26, title: 'GitHub Actions Documentation', metadata: { type: 'doc', url: 'https://docs.github.com/en/actions', topics: ['se-topic-6', 'se-topic-7'] } },
  { id: 'se-res-27', track: 'resource', sort_order: 27, title: 'Jest Documentation', metadata: { type: 'doc', url: 'https://jestjs.io/docs/getting-started', topics: ['se-topic-6', 'se-topic-13'] } },
  { id: 'se-res-28', track: 'resource', sort_order: 28, title: 'Playwright Documentation', metadata: { type: 'doc', url: 'https://playwright.dev/docs/intro', topics: ['se-topic-6', 'se-topic-13', 'se-topic-7'] } },
  { id: 'se-res-29', track: 'resource', sort_order: 29, title: 'Supabase Documentation', metadata: { type: 'doc', url: 'https://supabase.com/docs', topics: ['se-topic-4', 'se-topic-10'] } },
  { id: 'se-res-30', track: 'resource', sort_order: 30, title: 'Render Documentation', metadata: { type: 'doc', url: 'https://docs.render.com/', topics: ['se-topic-4', 'se-topic-7'] } },
  { id: 'se-res-31', track: 'resource', sort_order: 31, title: 'Railway Documentation', metadata: { type: 'doc', url: 'https://docs.railway.app/', topics: ['se-topic-4', 'se-topic-7'] } },
  { id: 'se-res-32', track: 'resource', sort_order: 32, title: 'Fly.io Documentation', metadata: { type: 'doc', url: 'https://fly.io/docs/', topics: ['se-topic-4', 'se-topic-7'] } },
  // Articles (7) + 1 doc
  { id: 'se-res-33', track: 'resource', sort_order: 33, title: 'Designing a Rate Limiter: 4 Algorithms, Real Trade-Offs', metadata: { type: 'article', url: 'https://dev.to/gabrielanhaia/designing-a-rate-limiter-4-algorithms-real-trade-offs-3h5', topics: ['se-topic-6', 'se-topic-7'] } },
  { id: 'se-res-34', track: 'resource', sort_order: 34, title: 'How API Rate Limiting Works', metadata: { type: 'article', url: 'https://mohamed-hendawy.medium.com/how-api-rate-limiting-works-fixed-window-token-bucket-sliding-window-explained-c16521f3e0e6', topics: ['se-topic-6', 'se-topic-7'] } },
  { id: 'se-res-35', track: 'resource', sort_order: 35, title: 'The different types of testing in software (Atlassian)', metadata: { type: 'article', url: 'https://www.atlassian.com/continuous-delivery/software-testing/types-of-software-testing', topics: ['se-topic-6', 'se-topic-13'] } },
  { id: 'se-res-36', track: 'resource', sort_order: 36, title: 'Types of software testing (Tricentis)', metadata: { type: 'article', url: 'https://www.tricentis.com/learn/software-testing-types', topics: ['se-topic-6', 'se-topic-13'] } },
  { id: 'se-res-37', track: 'resource', sort_order: 37, title: 'Unit vs Integration vs System vs E2E Testing (Microsoft)', metadata: { type: 'article', url: 'https://microsoft.github.io/code-with-engineering-playbook/automated-testing/e2e-testing/testing-comparison/', topics: ['se-topic-6', 'se-topic-13'] } },
  { id: 'se-res-38', track: 'resource', sort_order: 38, title: 'Software requirement document template (Asana)', metadata: { type: 'article', url: 'https://asana.com/resources/software-requirement-document-template', topics: ['se-topic-2', 'se-topic-3'] } },
  { id: 'se-res-39', track: 'resource', sort_order: 39, title: 'Trunk-Based Development vs. Gitflow (Flagsmith)', metadata: { type: 'article', url: 'https://www.flagsmith.com/blog/trunk-based-development-vs-gitflow', topics: ['se-topic-6'] } },
  { id: 'se-res-40', track: 'resource', sort_order: 40, title: 'Refactoring Guru — Design Patterns', metadata: { type: 'doc', url: 'https://refactoring.guru/design-patterns', topics: ['se-topic-1', 'se-topic-12'] } },
];
